#!/usr/bin/env sh

echo 'Checking Python version...'

# Get python version
version="$(python3 --version 2>&1)"

# Extract the first word
python="$(echo $version | cut -d ' ' -f 1)"

# If the first word isn't python, assume Python3 isn't installed and exit
if [ $python != "Python" ]; then
    echo 'Python 3 not installed. Install Python3 and run again.'
    exit 1
fi

# First get the numerical version (e.g. 3.4.4) then create a number for it (e.g. 34)
numversion=$(echo $version | cut -d ' ' -f 2)
num="$(echo $numversion | cut -d '.' -f 1)$(echo $numversion | cut -d '.' -f 2)"
 
# If the number < 34 (version is older than 3.4) exit
if [ $num -lt 34 ]; then 
    echo 'Wrong python 3 version; update to at least 3.4.'
    exit 1
else
    echo 'Python version is current'
fi  

# Get pip module version
pypip="$(python3 -m pip --version 2>&1)"

# Extract the word pip if pip module is installed
err="$(echo $pypip | cut -d ' ' -f 1)"

# If pip module inst't installed, check for program
if [ "$err" != "pip" ];then
    # Get/extract pip version (in case pip module is installed but pip isn't)
    pip="$(pip --version)"
    piperr="$(echo $pip | cut -d ' ' -f 5-)"
    
    # If neither version is found, exit
    if [ "$piperr" = "not found" ]; then
        echo "Pip not found; install pip and run again."
        exit 1
    else
        # Otherwise install modules through pip
        echo "Installing python modules through pip..."
        sudo pip install -q beautifulsoup4 requests lxml
    fi
else
    # Install through pip if available
    echo "Installing python modules through pip module..."
    sudo python3 -m pip install -q beautifulsoup4 requests lxml
fi

# If direcory doesn't already exist create directory
if [ ! -d ~/.PPE/ ]; then
    echo "Creating ~/.PPE/"
    mkdir ~/.PPE
fi
 
echo "Copying files to ~/.PPE/"
cp phoenixChecker.py ~/.PPE/phoenixChecker.py
cp phoenixClass.py ~/.PPE/phoenixClass.py
 
echo "Installing Phoenix-Parse-Email"
sudo cp phoenix /usr/bin/phoenix
