#!/bin/bash

while [ "$1" != "" ]; do
    case $1 in
        add )           	exec python3 ~/Phoenix-parse-email/add.py
                                ;;
        set )    		exec python3 ~/Phoenix-parse-email/setInterval.py
                                ;;
        run )           	exec python3 ~/Phoenix-parse-email/run.py
				exit 1
    esac
    shift
done
